CREATE TABLE storeusers(
    USER_ID int(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    USERS_UIDNM TINYTEXT NOT NULL,
    USERS_UNM LONGTEXT NOT NULL,
    USERS_PWD TINYTEXT NOT NULL,
    USERS_EMAIL TINYTEXT NOT NULL
);

CREATE TABLE cart (
    CART_ID int(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    product_name TINYTEXT NOT NULL,
    product_url TINYTEXT NOT NULL,
    product_id TINYTEXT NOT NULL,
    product_img_url TINYTEXT NOT NULL,
    product_price TINYTEXT NOT NULL,
    product_rating TINYTEXT NOT NULL,
    product_availability TINYTEXT NOT NULL,
    CART_UserID INT NOT NULL,
    FOREIGN KEY (CART_UserID) REFERENCES storeusers(USER_ID)
);